// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: baby/template/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Comply with lint rule of COMMENTS in buf.yaml
// QueryTemplateRequest is request of Template query service
type QueryTemplateRequest struct {
	Field uint64 `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (m *QueryTemplateRequest) Reset()         { *m = QueryTemplateRequest{} }
func (m *QueryTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTemplateRequest) ProtoMessage()    {}
func (*QueryTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d54f0814d7d3cfd3, []int{0}
}
func (m *QueryTemplateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTemplateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTemplateRequest.Merge(m, src)
}
func (m *QueryTemplateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTemplateRequest proto.InternalMessageInfo

func (m *QueryTemplateRequest) GetField() uint64 {
	if m != nil {
		return m.Field
	}
	return 0
}

// Comply with lint rule of COMMENTS in buf.yaml
// QueryTemplateResponse is response of Template query service
type QueryTemplateResponse struct {
	Field   uint64 `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	Field_1 string `protobuf:"bytes,2,opt,name=field_1,json=field1,proto3" json:"field_1,omitempty"`
}

func (m *QueryTemplateResponse) Reset()         { *m = QueryTemplateResponse{} }
func (m *QueryTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTemplateResponse) ProtoMessage()    {}
func (*QueryTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d54f0814d7d3cfd3, []int{1}
}
func (m *QueryTemplateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTemplateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTemplateResponse.Merge(m, src)
}
func (m *QueryTemplateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTemplateResponse proto.InternalMessageInfo

func (m *QueryTemplateResponse) GetField() uint64 {
	if m != nil {
		return m.Field
	}
	return 0
}

func (m *QueryTemplateResponse) GetField_1() string {
	if m != nil {
		return m.Field_1
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryTemplateRequest)(nil), "baby.template.QueryTemplateRequest")
	proto.RegisterType((*QueryTemplateResponse)(nil), "baby.template.QueryTemplateResponse")
}

func init() { proto.RegisterFile("baby/template/query.proto", fileDescriptor_d54f0814d7d3cfd3) }

var fileDescriptor_d54f0814d7d3cfd3 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0x3b, 0x31,
	0x18, 0xc6, 0x9b, 0xf2, 0x6f, 0xff, 0x1a, 0x70, 0x39, 0x2a, 0xd6, 0x43, 0x42, 0xa9, 0x0e, 0x45,
	0xf4, 0xe2, 0xd5, 0xc5, 0xd9, 0xc1, 0xc5, 0xc9, 0xe2, 0xe4, 0x22, 0x49, 0xfb, 0x1a, 0x0f, 0xee,
	0xee, 0x4d, 0x2f, 0x69, 0xb1, 0x88, 0x8b, 0x5f, 0x40, 0xc1, 0xc9, 0x6f, 0xe4, 0x58, 0x70, 0x71,
	0x94, 0xd6, 0x0f, 0x22, 0xcd, 0x5d, 0xc5, 0x4a, 0x75, 0x7b, 0xc3, 0xf3, 0xcb, 0x8f, 0x87, 0x87,
	0x6e, 0x4a, 0x21, 0x47, 0xdc, 0x42, 0xa2, 0x63, 0x61, 0x81, 0xf7, 0x07, 0x90, 0x8d, 0x02, 0x9d,
	0xa1, 0x45, 0x6f, 0x6d, 0x16, 0x05, 0xf3, 0xc8, 0xaf, 0x29, 0x54, 0xe8, 0x12, 0x3e, 0xbb, 0x72,
	0xc8, 0xdf, 0x52, 0x88, 0x2a, 0x06, 0x2e, 0x74, 0xc4, 0x45, 0x9a, 0xa2, 0x15, 0x36, 0xc2, 0xd4,
	0x14, 0xe9, 0x6e, 0x17, 0x4d, 0x82, 0x86, 0x4b, 0x61, 0x0a, 0x37, 0x1f, 0x86, 0x12, 0xac, 0x08,
	0xb9, 0x16, 0x2a, 0x4a, 0x1d, 0x5c, 0xb0, 0xfe, 0x62, 0x13, 0x2d, 0x32, 0x91, 0x14, 0x9e, 0xe6,
	0x1e, 0xad, 0x9d, 0xcd, 0x7e, 0x9f, 0x17, 0x69, 0x07, 0xfa, 0x03, 0x30, 0xd6, 0xab, 0xd1, 0xca,
	0x55, 0x04, 0x71, 0xaf, 0x4e, 0x1a, 0xa4, 0xf5, 0xaf, 0x93, 0x3f, 0x9a, 0x27, 0x74, 0xfd, 0x07,
	0x6d, 0x34, 0xa6, 0x06, 0x96, 0xe3, 0xde, 0x06, 0xfd, 0xef, 0x8e, 0xcb, 0xb0, 0x5e, 0x6e, 0x90,
	0xd6, 0x6a, 0xa7, 0xea, 0x9e, 0x61, 0xfb, 0x99, 0xd0, 0x8a, 0x13, 0x79, 0x0f, 0x84, 0xae, 0xcc,
	0x6d, 0xde, 0x76, 0xb0, 0x30, 0x4c, 0xb0, 0xac, 0x99, 0xbf, 0xf3, 0x37, 0x94, 0x17, 0x6a, 0x1e,
	0xdd, 0xbf, 0x7e, 0x3c, 0x95, 0xdb, 0xde, 0x01, 0xcf, 0x87, 0xda, 0xef, 0xc1, 0x10, 0x62, 0xd4,
	0x90, 0xf1, 0xc5, 0x35, 0xbe, 0x8e, 0x5b, 0xd7, 0xed, 0xee, 0xf8, 0xf4, 0x65, 0xc2, 0xc8, 0x78,
	0xc2, 0xc8, 0xfb, 0x84, 0x91, 0xc7, 0x29, 0x2b, 0x8d, 0xa7, 0xac, 0xf4, 0x36, 0x65, 0xa5, 0x8b,
	0x50, 0x45, 0xf6, 0x7a, 0x20, 0x83, 0x2e, 0x26, 0xbf, 0x58, 0x6f, 0xbe, 0x79, 0x47, 0x1a, 0x8c,
	0xac, 0xba, 0x95, 0x0f, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xb0, 0x37, 0x07, 0x0d, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Comply with lint rule of COMMENTS in buf.yaml
	// Template is a query template rpc service
	Template(ctx context.Context, in *QueryTemplateRequest, opts ...grpc.CallOption) (*QueryTemplateResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Template(ctx context.Context, in *QueryTemplateRequest, opts ...grpc.CallOption) (*QueryTemplateResponse, error) {
	out := new(QueryTemplateResponse)
	err := c.cc.Invoke(ctx, "/baby.template.Query/Template", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Comply with lint rule of COMMENTS in buf.yaml
	// Template is a query template rpc service
	Template(context.Context, *QueryTemplateRequest) (*QueryTemplateResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Template(ctx context.Context, req *QueryTemplateRequest) (*QueryTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Template not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Template_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Template(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/baby.template.Query/Template",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Template(ctx, req.(*QueryTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "baby.template.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Template",
			Handler:    _Query_Template_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baby/template/query.proto",
}

func (m *QueryTemplateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTemplateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTemplateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Field != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Field))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTemplateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTemplateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTemplateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Field_1) > 0 {
		i -= len(m.Field_1)
		copy(dAtA[i:], m.Field_1)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Field_1)))
		i--
		dAtA[i] = 0x12
	}
	if m.Field != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Field))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTemplateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Field != 0 {
		n += 1 + sovQuery(uint64(m.Field))
	}
	return n
}

func (m *QueryTemplateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Field != 0 {
		n += 1 + sovQuery(uint64(m.Field))
	}
	l = len(m.Field_1)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTemplateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTemplateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTemplateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field", wireType)
			}
			m.Field = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Field |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTemplateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTemplateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTemplateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field", wireType)
			}
			m.Field = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Field |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field_1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Field_1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
